var mongoose = require('mongoose');
var Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;
var itemSchema = new Schema({
    "_v":false,
    "StoreCode" : { type: Array },
    "skuday" : { type: String },
    "skucen" : { type: String },
    "skucur" : { type: String },
    "skuopc" : { type: String },
    "skustr" : { type: String },
    "inumbr" : { type: String },
    "idescr" : { type: String },
    "istyln" : { type: String },
    "iscolr" : { type: String },
    "issize" : { type: String },
    "iset" : { type: String },
    "isubst" : { type: String },
    "idsccd" : { type: String },
    "iprmpt" : { type: String },
    "idept" : { type: String },
    "isdept" : { type: String },
    "iclas" : { type: String },
    "isclas" : { type: String },
    "istype" : { type: String },
    "asnum" : { type: String },
    "islum" : { type: String },
    "pos18" : { type: String },
    "iposad" : { type: String },
    "iposcm" : { type: String },
    "iseasn" : { type: String },
    "icore" : { type: String },
    "istdpk" : { type: String },
    "mstbiz" : { type: String },
    "iatrsrl" : { type: String },
    "ipromo" : { type: String },
    "iatrfcc" : { type: String },
    "itaval" : { type: String },
    "iatrmrp" : { type: String },
    "iatremp" : { type: String },
    "iprcovr" : { type: String },
    "imsgflg" : { type: String },
    "imsgtyp" : { type: String },
    "orgprc" : { type: String },
    "ts_pull_dt" : { type: String },
    "correlation_id" : { type: String },
    "skugsu" : { type: String },
    "skucog" : { type: String },
    "skuuqc" : { type: String },
    "skucat" : { type: String },
    "skuhsn" : { type: String },
    "upc" : { type: Array },
    "tax" : { type: Array },
    "style" : { type: Array },
    "price" : { type: Array },
    "IsActive": { type: Boolean },
    "created_at": { type: Date },
    "updated_at": { type: Date },
}, { collection: 'ItemMaster' });
module.exports = mongoose.model('ItemMaster', itemSchema);