const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;
const OrdersSchema = new Schema({ 
    "invoice_no": { type: Number },
    "offline_invoice_no": { type: String },
    "master_order_id": { type: String },
    "invoice_bos_number": { type: String },
    "order_no": { type: String },   
    "store_details": { type: Object },
    "order_type": { type: String },  
    "customer_details": [{ type: Object }],
    "item_details": [{ type: Object }],
    "payment_details": [{ type: Object }],
    "payment_payee_details": [{ type: Object }],
    "order_status": { type: String },
    "order_state": { type: String },
    "order_source": { type: String },
    "is_kot_printed": { type: Boolean },
    "is_order_sync": { type: Boolean },
    "order_source_code": { type: String },
    "is_void": { type: Boolean },
    "calender_date": { type: Date },
    "business_date": { type: Date },
    "date_time": { type: Date },    
    "hour": { type: Number },
    "minute": { type: Number },
    "applied_discount": { type: Array },
    "discount_amount": { type: Number },
    "discount_percent":{ type: Number },
    "total_discount": { type: Number },
    "total_item_tax": { type: Number },
    "total_gross_sale": { type: Number },
    "total_net_sale": { type: Number },
    "sub_total":{ type: Number },
    "initial_paid": { type: Number },
    "split_bill_type": { type: Number },
    "tip_amount": { type: Number },
    "tip_percentage": { type: Number },
    "transaction_grand_amount":{ type: Number },
    "cash_round_off":{ type: Number },
    "change_tender":{ type: Number },
    "rounded_total":{ type: Number },
    "comment": { type: String },
    "is_kot_printed" : {type : Boolean},
    "is_receipt_printed": {type : Boolean},
    "is_tax_exempt": {type : Boolean},
    "timestamp":{ type: Number },
    "created_at" : {type: Date },
    "updated_at": {type: Date }
}, { collection: 'orders_master', versionKey: false });
// make this available to our users in our Node applications
module.exports = mongoose.model('orders_master', OrdersSchema);