const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;
const schema = new Schema({
    "store_id" : { type: String },
    "store_industry" : { type: String },
    "parent_store_id" : { type: String },
    "store_type" : { type: String },
    "store_org_name" : { type: String },
    "store_name" : { type: String },
    "store_owner_name" : { type: String },
    "store_contact_no" : { type: String },
    "email_id" : { type: String },
    "store_ad1" : { type: String },
    "store_ad2" : { type: String },
    "store_city" : { type: String },
    "store_state" : { type: String },
    "store_zip" : { type: String },
    "store_country" : { type: String },
    "store_currency" : { type: String },
    "store_tagline" : { type: String },
    "store_timezone" : { type: String },
    "integration" : { type: String },
    "referencestr" : { type: String },    
    "store_plan" : { type: String },
    "subscription_start_date" : { type: Date },
    "subscription_end_date" : { type: Date },
    "store_logo" : { type: String },
    "is_printer_enabled" : { type: Boolean },
    "kitchen_printer_count" : { type: Number },
    "is_online_payment" : { type: Boolean },  
    "is_tip_enabled" : { type: Boolean } , 
    "is_scanner_enabled" : { type: Boolean }  ,
    "is_email_acitve" : { type: Boolean },
    "is_sms_active" : { type: Boolean },
    "is_separate": { type: Boolean },  
    "review_url" : { type: String },  
    "inventory_check" : { type: Boolean }, 
    "add_item_with_variant": { type: Boolean }, 
    "enable_online_payment":{ type: Boolean }, 
    "is_tent_screen" : { type: Boolean },  
    "is_sms_notification": {type:Boolean},
    "is_store_auto_ready" : { type: Boolean },      
    "status" : { type: Boolean }  
}, {versionKey: false, collection: 'store_master' });
module.exports = mongoose.model('store_master', schema);